import type { Metadata } from "next";
import { GeistMono } from "geist/font";
import { Instrument_Serif } from "next/font/google";
import "./globals.css";
import { AlertProvider } from "@/lib/alert-context";

const geistMono = GeistMono;

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://api.fontshare.com/v2/css?f[]=switzer@1,2&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${geistMono.variable} ${instrumentSerif.variable} antialiased`}
        style={{ fontFamily: "'Switzer', sans-serif" }}
      >
        <AlertProvider>
          {children}
        </AlertProvider>
      </body>
    </html>
  );
}
